{
 "title": "Crafting",
 "tags": [ "SLYA" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "starbase",
    "query": {
     "query": "select distinct(starbase) as starbase from starbase WHERE \"time\" >= '${__from:date:iso}' AND \"time\" <= '${__to:date:iso}' order by case when substr(starbase, 1, 3) = 'MRZ' then starbase else concat(' ',starbase::STRING) end"
    }
   },
   { "name": "interval", "query": "hourly,daily" }
  ]
 },
 "panels": [
  {
   "title": "Crafted",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \n  case when '$interval' = 'hourly' then date_bin(interval 1 hour, time, '1970-01-01T00:00:00Z') else date_bin(interval 1 day, time, '1970-01-01T00:00:00Z') end as mytime,\n  sum(amount) as '',\n  output\nFROM \"crafting\"\nWHERE \n  (starbase in(${starbase:singlequote}) )\n  and type='Output'\n  and \"time\" >= $__timeFrom \n  AND \"time\" <= $__timeTo \nGROUP BY mytime,output\norder by mytime,output\n"
    }
   ]
  },
  {
   "title": "Burned raw materials",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \n  case when '$interval' = 'hourly' then date_bin(interval 1 hour, time, '1970-01-01T00:00:00Z') else date_bin(interval 1 day, time, '1970-01-01T00:00:00Z') end as mytime,\n  sum(amount) as '',\n  input\nFROM \"crafting\"\nWHERE \n  (starbase in(${starbase:singlequote}) )\n  and type='Input'\n  and input in ('Arco','Biomass','Carbon','Copper Ore','Diamond','Hydrogen','Iron Ore','Lumanite','Nitrogen','Rochinol','Silica','Survey Data Unit','Titanium Ore')\n  and \"time\" >= $__timeFrom \n  AND \"time\" <= $__timeTo \nGROUP BY mytime,input\norder by mytime,input\n"
    }
   ]
  },
  {
   "title": "Burned fees (Atlas)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \n  case when '$interval' = 'hourly' then date_bin(interval 1 hour, time, '1970-01-01T00:00:00Z') else date_bin(interval 1 day, time, '1970-01-01T00:00:00Z') end as mytime,\n  sum(fee) as ''\nFROM \"crafting\"\nWHERE \n  (starbase in(${starbase:singlequote}) )\n  and type='Input'\n  and \"time\" >= $__timeFrom \n  AND \"time\" <= $__timeTo \nGROUP BY 1\n"
    }
   ]
  }
 ]
}