{
 "title": "Mining",
 "tags": [ "SLYA" ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "starbase",
    "query": {
     "query": "select distinct(starbase) as starbase from mining WHERE \"time\" >= '${__from:date:iso}' AND \"time\" <= '${__to:date:iso}' order by case when substr(starbase, 1, 3) = 'MRZ' then starbase else concat(' ',starbase::STRING) end"
    }
   },
   { "name": "interval", "query": "hourly,daily" },
   {
    "name": "miner",
    "query": {
     "query": "select distinct(fleet) as fleet from mining WHERE \"time\" >= '${__from:date:iso}' AND \"time\" <= '${__to:date:iso}'"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Mined resources per interval",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \n  case when '$interval' = 'hourly' then date_bin(interval 1 hour, time, '1970-01-01T00:00:00Z') else date_bin(interval 1 day, time, '1970-01-01T00:00:00Z') end as mytime,\n  sum(amount) as '',\n  rss\nFROM \"mining\"\nWHERE \n  (starbase in(${starbase:singlequote}) )\n  and (fleet in(${miner:singlequote}) )\n  and \"time\" >= $__timeFrom \n  AND \"time\" <= $__timeTo \nGROUP BY mytime,rss\norder by mytime,rss\n"
    }
   ]
  },
  {
   "title": "Burned fuel (for mining)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \n  case when '$interval' = 'hourly' then date_bin(interval 1 hour, time, '1970-01-01T00:00:00Z') else date_bin(interval 1 day, time, '1970-01-01T00:00:00Z') end as mytime,\n  sum(`burnedFuel`) as `burned for mining`\nFROM \"mining\"\nWHERE \n  (starbase in(${starbase:singlequote}) )\n  and \"time\" >= $__timeFrom \n  AND \"time\" <= $__timeTo \nGROUP BY 1"
    },
    {
     "dataset": "iox",
     "rawSql": "SELECT \n  case when '$interval' = 'hourly' then date_bin(interval 1 hour, time, '1970-01-01T00:00:00Z') else date_bin(interval 1 day, time, '1970-01-01T00:00:00Z') end as mytime,\n  sum(`burnedFuel`) as `burned for moving`\nFROM \"movement\"\nWHERE \n  assignment='Mine'\n  and fleet in (select distinct(fleet) from mining where \"time\" >= $__timeFrom AND \"time\" <= $__timeTo and (starbase in(${starbase:singlequote}) ) )\n  and \"time\" >= $__timeFrom \n  AND \"time\" <= $__timeTo \nGROUP BY 1\n"
    }
   ]
  },
  {
   "title": "Burned Food",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \n  case when '$interval' = 'hourly' then date_bin(interval 1 hour, time, '1970-01-01T00:00:00Z') else date_bin(interval 1 day, time, '1970-01-01T00:00:00Z') end as mytime,\n  sum(`burnedFood`)\nFROM \"mining\"\nWHERE \n  (starbase in(${starbase:singlequote}) )\n  and \"time\" >= $__timeFrom \n  AND \"time\" <= $__timeTo \nGROUP BY 1\n"
    }
   ]
  },
  {
   "title": "Burned ammo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \n  case when '$interval' = 'hourly' then date_bin(interval 1 hour, time, '1970-01-01T00:00:00Z') else date_bin(interval 1 day, time, '1970-01-01T00:00:00Z') end as mytime,\n  sum(`burnedAmmo`)\nFROM \"mining\"\nWHERE \n  (starbase in(${starbase:singlequote}) )\n  and \"time\" >= $__timeFrom \n  AND \"time\" <= $__timeTo \nGROUP BY 1\n"
    }
   ]
  }
 ]
}