{
 "title": "Scanning",
 "tags": [ "SLYA" ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "ScanningFleets",
    "query": {
     "query": "select distinct(fleet) as fleet from sdu WHERE time >= '${__from:date:iso}' AND time <= '${__to:date:iso}'"
    }
   },
   { "name": "interval", "query": "hourly, daily" }
  ]
 },
 "panels": [
  { "title": "${ScanningFleets.label}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "SDUs/interval vs Scans/interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \n  case when '$interval' = 'hourly' then date_bin(interval 1 hour, time, '1970-01-01T00:00:00Z') else date_bin(interval 1 day, time, '1970-01-01T00:00:00Z') end as mytime,\n  sum(amount) as amount, \n  count(*) as count \nFROM \"sdu\" \nWHERE \n  (fleet in(${ScanningFleets:singlequote}) )\n  and \"time\" >= $__timeFrom \n  AND \"time\" <= $__timeTo \nGROUP BY 1,mytime\n"
    }
   ]
  },
  {
   "title": "Average sector chance / interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \n  case when '$interval' = 'hourly' then date_bin(interval 1 hour, time, '1970-01-01T00:00:00Z') else date_bin(interval 1 day, time, '1970-01-01T00:00:00Z') end as mytime,\n  avg(chance) as chance \nFROM \"sdu\" \nWHERE \n  (fleet in(${ScanningFleets:singlequote}) )\n  and \"time\" >= $__timeFrom \n  AND \"time\" <= $__timeTo \nGROUP BY 1"
    }
   ]
  },
  {
   "title": "Average fleet success rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \n  case when '$interval' = 'hourly' then date_bin(interval 1 hour, time, '1970-01-01T00:00:00Z') else date_bin(interval 1 day, time, '1970-01-01T00:00:00Z') end as mytime,\n  sum(case when amount = 0.0 then 0.0 else 1.0 end) / count(*) * 100 as `success rate`\nFROM \"sdu\" \nWHERE \n  (fleet in(${ScanningFleets:singlequote}) )\n  and \"time\" >= $__timeFrom \n  AND \"time\" <= $__timeTo \nGROUP BY 1,mytime"
    }
   ]
  },
  {
   "title": "Burned food / interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \ncase when '$interval' = 'hourly' then date_bin(interval 1 hour, time, TIMESTAMP '1970-01-01 00:00:00Z') else date_bin(interval 1 day, time, TIMESTAMP '1970-01-01 00:00:00Z') end as time, \nsum(\"burnedFood\") as burnedFood\nFROM sdu\nWHERE (fleet in(${ScanningFleets:singlequote}) ) and time >= $__timeFrom AND time <= $__timeTo group by 1 order by 1"
    }
   ]
  },
  {
   "title": "Burned fuel / interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \ncase when '$interval' = 'hourly' then date_bin(interval 1 hour, time, TIMESTAMP '1970-01-01 00:00:00Z') else date_bin(interval 1 day, time, TIMESTAMP '1970-01-01 00:00:00Z') end as time, \nsum(`burnedFuel`) as burnedFuel\nFROM movement \nWHERE (fleet in(${ScanningFleets:singlequote}) ) \nand assignment = 'Scan'\nand time >= $__timeFrom AND time <= $__timeTo \ngroup by 1 order by 1"
    }
   ]
  }
 ]
}