{
 "title": "Starbases",
 "tags": [ "SLYA" ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "starbase",
    "query": {
     "query": "select distinct(starbase) as starbase from starbase WHERE \"time\" >= '${__from:date:iso}' AND \"time\" <= '${__to:date:iso}' order by case when substr(starbase, 1, 3) = 'MRZ' then starbase else concat(' ',starbase::STRING) end"
    }
   },
   { "name": "r3", "query": "Ammunition,Food,Fuel" }
  ]
 },
 "panels": [
  {
   "title": "${r3}",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "repeat": "r3",
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \n  time,\n  first_value(`curAmount`) as $r3,\n  rss\nFROM \"starbase\" \nWHERE \n  (starbase in(${starbase:singlequote}) )\n  and (rss in(${r3:singlequote}) )\n  and \"time\" >= $__timeFrom \n  AND \"time\" <= $__timeTo \nGROUP BY 1,rss\norder by time"
    }
   ]
  },
  {
   "title": "Starbase inventory",
   "type": "timeseries",
   "gridPos": { "h": 21, "w": 16, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \n  time,\n  sum(`curAmount`) as '',\n  rss\nFROM \"starbase\" \nWHERE \n  (starbase in(${starbase:singlequote}) )\n  and (rss not in('Ammunition','Food','Fuel') )\n  and \"time\" >= $__timeFrom \n  AND \"time\" <= $__timeTo \nGROUP BY 1,rss\norder by rss"
    }
   ]
  },
  {
   "title": "Incoming rss per fleet",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "select \n  fleet, rss, sum(case when type in ('cargo_in','fuel_in','ammo_in') then amount*-1 else amount end) as amount\nfrom fleetrss where (starbase in(${starbase:singlequote}) ) and \"time\" >= $__timeFrom  AND \"time\" <= $__timeTo \nand type in ('cargo_out','fuel_out','ammo_out')\ngroup by fleet,rss order by fleet\n"
    }
   ]
  },
  {
   "title": "Outgoing rss per fleet",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "select \n  fleet, rss, sum(case when type in ('cargo_in','fuel_in','ammo_in') then amount*-1 else amount end) as amount\nfrom fleetrss where (starbase in(${starbase:singlequote}) ) and \"time\" >= $__timeFrom  AND \"time\" <= $__timeTo \nand type in ('cargo_in','fuel_in','ammo_in')\ngroup by fleet,rss order by fleet\n"
    }
   ]
  }
 ]
}